### ISSUE TITLE
Icon / graphics

### ISSUE THREAD

**Issue by neynah** [zombiezen/sandpass#1]
Hi Ross, let me know if you have any ideas. If not, I'll try to come up with some reasonable concepts/drafts sometime this week.

**Comment by zombiezen** [comment]
Most of the other ports of Keepass I've seen use a variant of the http://keepass.info/ lock logo (top-left), but https://www.keepassx.org/ has a distinctive X-like logo, which I like because it incorporates the key.

**Comment by zombiezen** [comment]
I'm going with the Material Design [Orange color palette](https://www.google.com/design/spec/style/color.html#color-color-palette) for the UI elements.

**Comment by neynah** [comment]
@zombiezen so are you thinking you'd like an orange version of that logo? I had to revector it since I couldn't find a higher-resolution image. It'll be easy to change the colours from here. I can add the drop shadow as well if you prefer but I think it sort of looks dated!
![image](https://cloud.githubusercontent.com/assets/855341/14896188/5c8d93d4-0d31-11e6-9eb7-9512aac747c1.png)

**Comment by zombiezen** [comment]
Nice! LGTM

**Comment by zombiezen** [comment]
Hey @neynah: sorry about this, but after reviewing the licensing for the KeePassX icons, I think using them (even a derivative) would mean that I would need to license the whole app as GPLv2, which I would prefer not to do (I like the Apache 2.0 license).  Would you be willing to design an alternate icon?

**Comment by neynah** [comment]
@zombiezen I'm happy to! Perhaps just a generic key?

**Comment by zombiezen** [comment]
:+1:

**Comment by neynah** [comment]
BTW, I will have this done before the end of Friday. :)

**Comment by zombiezen** [comment]
Great, thank you!

**Comment by neynah** [comment]
Thoughts on these? (Also happy to come up with others)

![image](https://cloud.githubusercontent.com/assets/855341/17942471/5c184378-69ec-11e6-900c-55c91b975d92.png)

I'll design the full set of icons once I know what your preferences are.

**Comment by zombiezen** [comment]
Terrific! I like the one on the left.  It does seem like the left-most edge blends a bit into the background, but I'm not sure what I'd suggest to add definition there.  It's a small nit, tho, this looks great to me if you want to move forward with making the full icon set. :+1: :+1: :+1:

**Comment by neynah** [comment]
Thanks for getting back to me so quickly. Yeah I sort of blended it in purposely but I can adjust it for sure. :D Sounds great, I'll make some tweaks and submit a PR soonish.
