### ISSUE TITLE
Cannot delete groups

### ISSUE THREAD

**Issue by ndarilek** [zombiezen/sandpass#27]
Steps to reproduce:

1. Create a new grain.
2. Enter a password and click Create.
3. Click the Misc group.
4. Click Delete.
5. Click Delete again, or whatever the confirmation button is.

Results: I'm bounced back to the password entry screen, told that my session is invalid, prompted to re-enter a password, and the group still exists.

**Comment by zombiezen** [comment]
I am unable to reproduce this on Oasis.  The error message you are seeing is one that occurs when a session cookie expires (currently [30 minutes](https://github.com/zombiezen/sandpass/blob/7cba352de039871f9b1b035d2ba30aeec90dfc76/session.go#L30)).  This would produce the behavior you are seeing, where the deletion would not have taken place.  If there's a good case for making that timeout customizable, I'd be happy to change it.

Related: #16 is a known issue where you cannot delete non-empty groups.

And unrelated: I remember from the Sandstorm lists that you give great accessibility feedback.  Let me know if you have any feedback; I tried quite a bit to make the UI accessible.

**Comment by ndarilek** [comment]
Hey, thanks for the interest in accessibility!

Interesting, there is little delay in performing these actions. It 
happens on a new Sandstorm server, non-Oasis. I'm basically creating the 
database, then trying to delete all the default groups to create my own.

I'll take a look at the server logs to see if anything is happening.

**Comment by ndarilek** [comment]
Closing this as I've found a partial cause, and it *isn't* Sandpass. Somehow I have some bad cookies which also caused Roundcube to get stuck in a Firefox-detected redirect loop. Deleting all cookies for the affected Sandstorm instances made both the Roundcube issue and this problem go away.

Now to figure out who's poisoning my cookies...

**Comment by zombiezen** [comment]
Got it, that sounds like it would cause what you're seeing.  Good luck!
